language: python
python:
  - "3.6"
addons:
  postgresql: "10"
env:
  - DJANGO=2.2 DB=postgres
  - PGPORT=5433
before_install:
  - export DJANGO_SETTINGS_MODULE=settings.staging_test
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database testdb;' -U postgres
script:
  - python manage.py test