language: python
python:
  - "3.7"
services:
  - postgresql
env:
  - DJANGO=2.2 DB=postgresql
  - export DJANGO_SETTINGS_MODULE=settings.staging_test
install:
  - pip install -r requirements.txt
before_script:
  - postgresql -e 'create database test;' -u root
script:
  - python manage.py test