language: python
    services:
      - postgresql
    test:
      adapter: postgresql
      database: travis_ci_test
    install: # => 5
      - pip install -r requirements.txt
    before_script: # => 6
      - psql -c 'create database travis_ci_test;' -U postgres
    script: # => 7
      - python manage.py test
