language: python
python:
  - "3.6"
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  - DJANGO=2.2 DB=postgres DJANGO_SETTINGS_MODULE=settings.staging_test PGPORT=5433
install:
  - pip install -r requirements.txt
before_script:
  - rm -rf users/migrations/00*
  - rm -rf recipes/migrations/00*
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - python manage.py makemigrations
  - python manage.py migrate --noinput
  - python manage.py test