language: python
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
install:
  - pip install -r requirements.txt
  - psql -c 'create database test_db;' -U postgres
script:
  - export DJANGO_SETTINGS_MODULE=settings.staging_test
  - python manage.py test
