dist: xenial
language: python
virtualenv:
  system_site_packages: true
install:
  - pip install -r requirements.txt
script:
  - export DJANGO_SETTINGS_MODULE=settings.staging_test
  - python manage.py test