language: python
services: postgresql
env:
  - export DJANGO_SETTINGS_MODULE=settings.staging_test
install:
  - pip install -r requirements.txt
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
