language: python
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  - DJANGO=2.2.1
  global:
  - PGPORT=5433
before_install:
  - export DJANGO_SETTINGS_MODULE=settings.staging_test
install:
  - pip install -r requirements.txt
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
