language: python
services:
  - postgresql
python:
  - "3.6"
env:
- DJANGO=2.2 DB=postgres
before_install:
- export DJANGO_SETTINGS_MODULE=settings.staging_test
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database testdb;' -U postgres
script:
- python manage.py test