version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=recipe
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "./data/db:/var/lib/postgresql/data"
  web:
    build: .
    volumes:
      - "./code"
    environment:
      - DJANGO_SETTINGS_MODULE=settings.local
    ports:
      - "8000:8000"
    restart: unless-stopped
    tty: true
    depends_on:
      - db
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - db
      - web