version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=recipe
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - "./data/db:/var/lib/postgresql/data"
  redis:
    image: "redis:alpine"
  web:
    build: .
    volumes:
      - "./code"
    environment:
      - DJANGO_SETTINGS_MODULE=settings.local
    restart: unless-stopped
    tty: true
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A HipoProject worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A HipoProject beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - db
      - web